name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java_version: [1.8, 11, 13]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Build with Gradle
      run: ./gradlew check
